validation added to entities and value objects
Percimon/PetHomeFinder pull request #11
Opened 2024-09-12 22:55 UTC by Percimon

2024-09-13 07:25 UTC, KirillSachkov requested changes

2024-09-13 07:25 UTC, KirillSachkov commented on backend/src/PetHomeFinder.Domain/PetManagement/ValueObjects/PetPhotoList.cs
> +    public static Result<PetPhotoList> Create(IEnumerable<PetPhoto> petPhotos)
в данном случае нет необходимости в таком методе, потому что нет никакой валадиции, лучше сделать конструктор публичным

2024-09-13 07:25 UTC, KirillSachkov commented on backend/src/PetHomeFinder.Domain/PetManagement/ValueObjects/SocialNetworkList.cs
> +        public static Result<SocialNetworkList> Create(IEnumerable<SocialNetwork> socialNetworks)
здесь также

2024-09-14 18:37 UTC, YaraOduvanchik approved these changes

2024-09-14 19:55 UTC, merged