domain refactoring, config updated
Percimon/PetHomeFinder pull request #8
Opened 2024-08-29 20:21 UTC by Percimon

2024-08-29 21:22 UTC, YADARAN1 requested changes

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Domain/PetManagement/ValueObjects/Address.cs
> +    public static Address Create(string city, string district, string street, string structure) =>
Сделать валидацию

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Domain/PetManagement/ValueObjects/Height.cs
> +        return new Height(value);
Сделать валидацию

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Domain/PetManagement/ValueObjects/PetPhoto.cs
> +            return new PetPhoto(filePath, isMain);
Сделать валидацию

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Domain/PetManagement/ValueObjects/Weight.cs
> +        return new Weight(value);
Сделать валидацию

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Domain/SpeciesManagement/Entities/Breed.cs
> +    {
Допилить класс

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Infrastructure/Configurations/PetConfiguration.cs
> +                        cb.ToJson();
в скобках указать название в snakecase стиле

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Infrastructure/Configurations/PetConfiguration.cs
> +                        pb.ToJson();
в скобках указать название в snakecase стиле

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Infrastructure/Configurations/VolunteerConfiguration.cs
> +                    .IsRequired()
в скобках указать название в snakecase стиле
![image](https://github.com/user-attachments/assets/45f441ef-41a3-450a-9c79-c3e589e434b2)

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Infrastructure/Configurations/VolunteerConfiguration.cs
> +
в скобках указать название в snakecase стиле
![image](https://github.com/user-attachments/assets/1d74aa21-56ea-461f-b020-f5f13fecb940)

2024-08-29 21:22 UTC, YADARAN1 commented on backend/src/PetHomeFinder.Infrastructure/Configurations/SpeciesConfiguration.cs
> +           .OnDelete(DeleteBehavior.Cascade);
Нам не нужно выпиливать породы, если мы удалим какой-то вид

2024-08-31 10:55 UTC, Asasen1 approved these changes

2024-08-31 16:49 UTC, merged